### ISSUE TITLE
Support OpenCV >=4.1

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#114]
It would be great to support 3.8 for this package.

I've had to install Python 3.6 from the AUR to use it :(

**Comment by RealOrangeOne** [comment]
I can't think of anything which specifically would cause an issue.

What issues are you seeing when installing?

**Comment by trickeydan** [comment]
There's a restriction on the version of OpenCV. The current maximum supported version does not have wheels for 3.8 on PyPI.

So this is more about supporting OpenCV 4.1.x I guess.

**Comment by RealOrangeOne** [comment]
Looks like the primary issue is the lack of wheels for `opencv-contrib-python-headless<4.2`.

That's something I've been meaning to look into, so I'm going to re-purpose this issue.

**Comment by trickeydan** [comment]
Upstream issue: https://github.com/skvark/opencv-python/issues/280

**Comment by RealOrangeOne** [comment]
Fixed by #285
