### ISSUE TITLE
Rename `marker_dict` to `marker_type`

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/zoloto#117]
To keep a distinction, the `marker_dict` is really just a key to be used ton construct what becomes the actual marker dictionary, so we should rename it. This should make the code far less confusing!

Should be done after #118 merges.

**Comment by trickeydan** [comment]
Please don't publish this in 0.4.x, it's a super breaking change.

**Comment by RealOrangeOne** [comment]
> Please don't publish this in 0.4.x, it's a super breaking change.

I am aware.
