### ISSUE TITLE
Camera discovery prints OpenCV errors

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#144]
```
VIDEOIO ERROR: V4L2: Could not obtain specifics of capture window.
VIDEOIO ERROR: V4L: can't open camera by index 1
/dev/video1 does not support memory mapping
VIDEOIO ERROR: V4L: can't open camera by index 2
VIDEOIO ERROR: V4L: can't open camera by index 3
VIDEOIO ERROR: V4L: can't open camera by index 4
VIDEOIO ERROR: V4L: can't open camera by index 5
VIDEOIO ERROR: V4L: can't open camera by index 6
VIDEOIO ERROR: V4L: can't open camera by index 7
```

I'm aware this issue is known, but I would like to track it in an issue so we can keep an eye on it.

This currently forcefully outputs text for each camera, which is annoying. This will be fixed once opencv/opencv#15111 is released into OpenCV wheels.

**Comment by RealOrangeOne** [comment]
I'm less convinced this is something `zoloto` should do something about. The logs are annoying, yes, but with https://github.com/opencv/opencv/pull/15111 shipped it can be controlled using `OPENCV_LOG_LEVEL=ERROR`, which can and should be left up to the downstream consumer.
