### ISSUE TITLE
Deliver examples in package

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/zoloto#160]
The `examples/` package contains a couple generally useful scripts, which I find handy during development, and for demos.

It might be an idea to vendor these in to the package (as part of the CLI) so they can be used downstream.

**Comment by trickeydan** [comment]
Related: #113

**Comment by trickeydan** [comment]
> It might be an idea to vendor these in to the package (as part of the CLI) so they can be used downstream.

This would be super helpful!
