### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/zoloto#205]
Python 3.5 will be EoL in September ([src](https://devguide.python.org/#status-of-python-branches)), so there's no point keeping it around.

Removing support for this will also make typing a bit easier, as 3.6 massively improved Python's typing story.

**Comment by trickeydan** [comment]
c2295d4e702427f2fa7efbb9e43178dcf025a7ee should be reverted when we do this.
