### ISSUE TITLE
Should BaseCamera be abstract?

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#26]
I think that it definitely could be, and we wouldn't lose 3.5 support by implementing that, but will make it harder to misuse the library.

**Comment by RealOrangeOne** [comment]
Yes it definitely should be. I've been meaning to go back and make it abstract, but haven't had the time. I welcome a PR, though!

**Comment by RealOrangeOne** [comment]
The implementation for this is a little _odd_, as not only does `BaseCamera` need to be abstract, but so too do the majority of the specific cameras, as many of them rely on the end user overriding certain methods (namely `get_marker_size`).

Will need to do some more digging around on that!

**Comment by trickeydan** [comment]
See j5 for examples, abstract classes can extend other abstract ones. Indeed, the type checker on j5 managed to determine this magically.

I don't know if there is python 3.5 support, but `Protocol` may be what we need here

**Comment by RealOrangeOne** [comment]
The majority of cameras should be abstract actually. The only ones which shouldn't are the file cameras, although I think we should provide some util methods to help with those, ie `process_image('test.png', marker_size=250, ... )`.

Some further thought needs to be put into this one.
