### ISSUE TITLE
License

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#27]
We could really do with a licence on here.

**Comment by RealOrangeOne** [comment]
I'll get around to licensing it at some point, that'll probably come when I consider the package _stable_, which _might_ be by the end of the weekend.

**Comment by RealOrangeOne** [comment]
Fixed in https://github.com/RealOrangeOne/zoloto/commit/226e3bf10db9d11fc7a123b584b77cb64e4ba70c
