### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by trickeydan** [RealOrangeOne/zoloto#29]
This should be on PyPI, it's somewhat annoying to add as a dependency to j5 currently. Especially as there are no release versions.

**Comment by RealOrangeOne** [comment]
The library is currently considered 'Under Active Development', and functionally a beta. 

Once that changes, it'll be pushed to PyPI, along with #27

**Comment by trickeydan** [comment]
Packages on PyPI don't have to be stable. For example, `j5`.

See https://www.python.org/dev/peps/pep-0440/#pre-releases

**Comment by RealOrangeOne** [comment]
Fixed in https://github.com/RealOrangeOne/zoloto/commit/7084dade1c39f13fe583c3d0f1f0224ec3e1a708.

https://pypi.org/project/zoloto/
