### ISSUE TITLE
Use OpenCV 4

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/zoloto#56]
We want to use OpenCV 4, so we're using a more modern version, which contains a fair number of improvements: https://opencv.org/opencv-4-0/

Unfortunately, there are currently no wheels available for the Raspberry Pi (something we **need**). #54 reverted back to OpenCV 3, with minimal changes. It's hoped that once OpenCV 4 wheels are available, they'll be a lot more performant, which is great!

Unfortunately, this is blocked on https://github.com/piwheels/packages/issues/28 and https://github.com/piwheels/piwheels/issues/189.

**Comment by trickeydan** [comment]
This issue is now unblocked :tada: 

Source: https://github.com/piwheels/packages/issues/28#issuecomment-550432763
